# Generated by Django 4.2.6 on 2023-10-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=20)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
