# Generated by Django 4.2.6 on 2023-10-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
