# Generated by Django 4.2.6 on 2023-10-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_logo_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=20)),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('title', models.CharField(default=' ', max_length=150)),
                ('sub_title', models.TextField()),
            ],
        ),
    ]
