# Generated by Django 4.0.3 on 2023-10-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuler_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=20)),
                ('title', models.CharField(default='hello', max_length=40)),
                ('sub_title', models.CharField(default='hello', max_length=80)),
                ('categories_background_image', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('categories_image', models.ImageField(blank=True, null=True, upload_to='slider/')),
            ],
        ),
    ]
