# Generated by Django 4.0.3 on 2023-10-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_producat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=20)),
                ('ss_coustomer_review', models.ImageField(blank=True, null=True, upload_to='coustomer_review/')),
            ],
        ),
    ]
